### ISSUE TITLE
bseqc mbias error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hutuqiu/bseqc#3]
```
What steps will reproduce the problem?
1. bseqc mbias -s my_data.bam -r my_genome.fa -l 101 -n test_mbias -g 841000000

What is the expected output? What do you see instead?
Program does not run to completion, terminal output is:

INFO  @ Sun, 29 Mar 2015 13:34:04: Get the all parameter!! 
 INFO  @ Sun, 29 Mar 2015 13:34:04: The input mapping files are paired-end sequencing! 
 INFO  @ Sun, 29 Mar 2015 13:34:04: The filter_dup has been set True. 
 INFO  @ Sun, 29 Mar 2015 13:34:04: QC_report not only includes Mbias plot, Mbias table and trimming file, but also Dup distribution. 
 INFO  @ Sun, 29 Mar 2015 13:34:04: Get reference sequences... 
 INFO  @ Sun, 29 Mar 2015 13:34:39: The reference has been got! 
 INFO  @ Sun, 29 Mar 2015 13:34:39: Calculate the M fraction for every position and record the location information in my_data.bam... 
 INFO  @ Sun, 29 Mar 2015 13:34:39: draw Mbias plot and export the Mbias table... 
 INFO  @ Sun, 29 Mar 2015 13:34:39: export the Mbias table... 
 INFO  @ Sun, 29 Mar 2015 13:34:39: Draw Mbias plot... 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/bseqc", line 214, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/bseqc", line 73, in main
    run(argparser)
  File "/Users/burtonigenomics/Documents/BSeQC_V1.3/BSeQC/mbias.py", line 120, in run
    strand_t, loc_dict, max_cov = QC_report_MD.generator()
  File "/Users/burtonigenomics/Documents/BSeQC_V1.3/BSeQC/qc_assess/qc_report.py", line 325, in generator
    MR.mbias_generator(strand_p[i], strand_t_each, name_context[i])
  File "/Users/burtonigenomics/Documents/BSeQC_V1.3/BSeQC/qc_assess/mbias_report.py", line 140, in mbias_generator
    length_max = max(length_list)
ValueError: max() arg is an empty sequence


What version of the product are you using? On what operating system?
BSeQC_V1.3, OSX 10.6.8

Please provide any additional information below.
Followed default installation instructions, no errors during install.
PYTHONPATH includes /usr/local/lib/python2.7/site-packages
PATH includes /user/local/bin

```

Original issue reported on code.google.com by `ahill...@gmail.com` on 29 Mar 2015 at 8:46

**Comment by hutuqiu** [comment]
Have you installed this python package: Matplotlib?

**Comment by mikeburen** [comment]
Wondering if this was resolved as I am seeing the same error:

bseqc 1.0.3
python 2.7
matplotlib 1.5.1+1823.g5416da2
redhat 6*

Tried the anaconda route, and the python route.. can't get past beyond the error above
