### ISSUE TITLE
KeyError: 'chr22'

### ISSUE THREAD

**Issue by bhappy2** [hutuqiu/bseqc#4]
bseqc mbias -s ./my.bam -r ../GRCh38.p3.fasta -o -t ~/seq-soft/samtools-0.1.19

 INFO  @ Sun, 13 Sep 2015 12:10:49: Get the all parameter!! 
 INFO  @ Sun, 13 Sep 2015 12:10:49: The input mapping files are paired-end sequencing! 
 INFO  @ Sun, 13 Sep 2015 12:10:49: The filter_dup has been set True. 
 INFO  @ Sun, 13 Sep 2015 12:10:49: QC_report not only includes Mbias plot, Mbias table and trimming file, but also Dup distribution. 
 INFO  @ Sun, 13 Sep 2015 12:10:49: Get reference sequences... 
 INFO  @ Sun, 13 Sep 2015 12:12:11: The reference has been got! 
 INFO  @ Sun, 13 Sep 2015 12:12:11: Calculate the M fraction for every position and record the location information in ./my.bam... 
Traceback (most recent call last):
  File "/usr/bin/bseqc", line 214, in <module>
    main()
  File "/usr/bin/bseqc", line 73, in main
    run(argparser)
  File "/usr/lib/python2.7/site-packages/BSeQC/mbias.py", line 120, in run
    strand_t, loc_dict, max_cov = QC_report_MD.generator()
  File "/usr/lib/python2.7/site-packages/BSeQC/qc_assess/qc_report.py", line 318, in generator
    strand_p, loc_dict = self.parser_sambam(strand_p, ref)
  File "/usr/lib/python2.7/site-packages/BSeQC/qc_assess/qc_report.py", line 278, in parser_sambam
    strand_p_CG = rm_pair_CG.record_meth()
  File "/usr/lib/python2.7/site-packages/BSeQC/read/C_information.py", line 180, in record_meth
    MethReader.record_meth(self)
  File "/usr/lib/python2.7/site-packages/BSeQC/read/C_information.py", line 117, in record_meth
    refseq = self.ref[chr][pos - 1:pos + readlen + 1]
KeyError: 'chr22'

**Comment by hutuqiu** [comment]
Are your reads paired-end? Could you show some reads for me?
